//获取渠道统计数据
export const FETCH_CHANNEL_REQUEST='FECTH_CHANNEL_REQUEST';
export const FETCH_CHANNEL_FAILURE='FETCH_CHANNEL_FAILURE';
export const FETCH_CHANNEL_SUCCESS='FETCH_CHANNEL_SUCCESS';

//获取渠道统计禁用数据时间段
export const FETCH_CHANNEL_DISABLEDDATE_REQUEST='FETCH_CHANNEL_DISABLEDDATE_REQUEST';
export const FETCH_CHANNEL_DISABLEDDATE_FAILURE='FETCH_CHANNEL_DISABLEDDATE_FAILURE';
export const FETCH_CHANNEL_DISABLEDDATE_SUCCESS='FETCH_CHANNEL_DISABLEDDATE_SUCCESS';

//时间改变
export const CHANNEL_DATE_CHANGE='CHANNEL_TIME_CHANGE';
