
export const FETCH_FAILURE='FETCH_FAILURE';//请求失败
export const FETCH_SUCCESS='FETCH_SUCCESS';//请求成功
export const FETCHING ='FETCHING';//请求中

export const FETCH_MEMBERS_SUCCESS = 'FETCH_MEMBERS_SUCCESS';//获取成员列表成功
export const FETCH_DEPTS_SUCCESS = 'FETCH_DEPTS_SUCCESS';//获取部门列表成功

export const FETCH_ALLGOAL_SUCCESS = 'FETCH_ALLGOAL_SUCCESS';//获取全部目标成功
export const FETCH_GOAL_STAT_SUCCESS = 'FETCH_GOAL_STAT_SUCCESS';//获取目标统计
export const FETCH_YEAR_RATE_SUCCESS = 'FETCH_YEAR_RATE_SUCCESS';//获取年完成率
export const GET_GOAL_SUCCESS = 'GET_GOAL_SUCCESS';//获取单个目标成功
export const SET_GOAL_SUCCESS = 'SET_GOAL_SUCCESS';//设置单个目标成功

export const FETCH_FUNNEL_DATE_SUCCESS = 'FETCH_FUNNEL_DATE_SUCCESS';//获取销售漏斗首页数据成功
export const FETCH_BILL_DATA_SUCCESS = 'FETCH_BILL_DATA_SUCCESS';//获取订单列表
export const FETCH_USER_RANK_SUCCESS = 'FETCH_USER_RANK_SUCCESS';//获取员工排行
export const FETCH_DEPT_RANK_SUCCESS = 'FETCH_DEPT_RANK_SUCCESS';//获取部门排行

