var json = {
    //我的客户
    "https://www.staticec.com/api/bootstrap/css/bootstrap.min.css": 1,
    "https://www.staticec.com/my/css/base.css": 1,
    "https://www.staticec.com/api/css/themes/base/jquery-ui.css": 1,
    "https://www.staticec.com/my/css/main.css": 1,
    "https://www.staticec.com/my/css/crm/crm.css": 1,
    "https://www.staticec.com/api/gallery/css/zoom.css": 1,
    "https://www.staticec.com/my/css/fixed/fixed.css": 1,
    "https://www.staticec.com/my/components/ec-components.css": 1,
    "https://www.staticec.com/my/scripts/prototype.js": 1,
    "https://www.staticec.com/my/scripts/common.js": 1,
    "https://www.staticec.com/api/scripts/jquery-1.8.2.min.js": 1,
    "https://www.staticec.com/api/scripts/ui/jquery-ui.min.js": 1,
    "https://www.staticec.com/api/scripts/jquery.sprintf.js": 1,
    "https://www.staticec.com/api/scripts/jquery.cookie.js": 1,
    "https://www.staticec.com/api/bootstrap/js/bootstrap.js": 1,
    "https://www.staticec.com/my/scripts/page_cookie.js": 1,
    "https://www.staticec.com/api/layerui/layer.js": 1,
    "https://www.staticec.com/api/scripts/ui/jquery.ui.widget.js": 1,
    "https://www.staticec.com/api/scripts/ui/jquery-ui-timepicker-addon.js": 1,
    "https://www.staticec.com/api/scripts/fileupload/jquery.fileupload.js": 1,
    "https://www.staticec.com/api/scripts/fileupload/jquery.fileupload-process.js": 1,
    "https://www.staticec.com/api/scripts/fileupload/jquery.fileupload-preview.min.js": 1,
    "https://www.staticec.com/api/scripts/fileupload/jquery.fileupload-validate.js": 1,
    "https://www.staticec.com/api/gallery/js/jquery.zoom.min.js": 1,
    "https://www.staticec.com/api/scripts/lazyload/jquery.lazyload.min.js": 1,
    "https://www.staticec.com/my/components/babel-polyfill.js": 1,
    "https://www.staticec.com/my/components/js/commons.js": 1,
    "https://www.staticec.com/my/components/js/ec-components.js": 1,
    "https://www.staticec.com/my/scripts/crm/ec_crm_corp.js": 1,
    "https://www.staticec.com/my/scripts/crm/ec_crm_detail.js": 1,
    "https://www.staticec.com/my/scripts/crm/crm_act_new.js": 1,
    "https://www.staticec.com/my/scripts/crm/ec_crm_annal.js": 1,
    "https://www.staticec.com/my/images/default_avatar.jpg": 1,
    "https://www.staticec.com/my/images/content/default-down-icon.png": 1,
    "https://www.staticec.com/my/images/crm/cloudboard/cloudboard.png": 1,
    "https://www.staticec.com/my/images/content/c_icon.png": 1,
    "https://www.staticec.com/my/images/content/ec_icon_new.png": 1,
    "https://www.staticec.com/my/images/down.png": 1,
    "https://www.staticec.com/api/images/scrollbar/scroll.png": 1,
    "https://www.staticec.com/my/images/err_icon.png": 1,
    "https://www.staticec.com/api/layerui/skin/layer.css": 1,
    "https://www.staticec.com/api/images/public/ec_bg_sprites.png": 1,
    "https://www.staticec.com/api/scripts/prototype/unsafe/prototype-1.7.min.js": 1,
    "https://www.staticec.com/api/scripts/jquery/unsafe/jquery-1.8.2.min.js": 1,
    "https://www.staticec.com/my/images/content/loading_03.gif": 1,
    "https://www.staticec.com/my/images/content/crm_icon_new.png": 1,
    "https://www.staticec.com/my/images/content/m_icon.png": 1
}

module.exports = json;