var json = {
    //客户详细资料
    "https://www.staticec.com/api/scripts/jquery/jquery-1.8.2.min.js": 1,
    "https://www.staticec.com/api/css/themes/base/jquery.ui.all.css": 1,
    "https://www.staticec.com/api/scripts/ui/jquery.ui.core.js": 1,
    "https://www.staticec.com/api/scripts/ui/jquery.ui.datepicker.js": 1,
    "https://www.staticec.com/my/scripts/jq_checkable.js": 1,
    "https://www.staticec.com/my/scripts/crm/ec_crm_index.js": 1,
    "https://www.staticec.com/my/scripts/crm/ec_tag_act.js": 1,
    "https://www.staticec.com/api/css/base.css": 1,
    "https://www.staticec.com/my/css/work.css": 1,
    "https://www.staticec.com/my/components/new-ec-com/comm.css": 1,
    "https://www.staticec.com/my/css/crm/crm_pc10_inside.css": 1,
    "https://www.staticec.com/api/bootstrap/js/bootstrap.min.js": 1,
    "https://www.staticec.com/api/scripts/ui/jquery.ui.mouse.js": 1,
    "https://www.staticec.com/api/scripts/ui/jquery.ui.draggable.js": 1,
    "https://www.staticec.com/api/scripts/ui/jquery.ui.sortable.js": 1,
    "https://www.staticec.com/my/scripts/crm/crm_pager_add.js": 1,
    "https://www.staticec.com/my/scripts/crm/ec_crm_act.2.js": 1,
    "https://www.staticec.com/my/scripts/third_analysis.js": 1,
    "https://www.staticec.com/my/scripts/crm/PV.js": 1,
    "https://www.staticec.com/my/scripts/pc_10_inside.1.js": 1,
    "https://www.staticec.com/api/images/arrow.png": 1,
    "https://www.staticec.com/my/images/crm/fdj.png": 1,
    "https://www.staticec.com/my/images/crm/1.9.1/sys_min_normal.png": 1,
    "https://www.staticec.com/my/images/crm/1.9.1/sys_close_normal.png": 1,
    "https://www.staticec.com/my/images/crm/1.9.1/sys_max_normal.png": 1,
    "https://www.staticec.com/my/images/crm/1.9.1/sys_restore_normal.png": 1,
    "https://www.staticec.com/my/images/crm/1.9.1/setting.png": 1,
    "https://www.staticec.com/my/images/crm/1.9.1/msg.png": 1,
    "https://www.staticec.com/my/images/crm/1.9.1/sys_corp_gray.png": 1,
    "https://www.staticec.com/my/images/crm/1.9.1/sys_per_white.png": 1,
    "https://www.staticec.com/api/scripts/nreport.js": 1,
    "https://www.staticec.com/api/css/themes/base/images/ui-bg_inset-hard_100_fcfdfd_1x100.png": 1,
    "https://www.staticec.com/my/images/checkable-blue.png": 1,
    "https://www.staticec.com/api/css/Validform_style.css": 1,
    "https://www.staticec.com/api/scripts/Validform_v5.3.js": 1,
    "https://www.staticec.com/my/scripts/crm/newcrm_user.js": 1,
    "https://www.staticec.com/my/css/main_cm.css": 1,
    "https://staticec.com/api/images/scrollbar/scroll.png": 1
}

module.exports = json;